name: Unit and Integration Tests

on: push

jobs:
  unit_and_int_tests:
    runs-on: ubuntu-latest
    name: Unit and Integration Tests
    env:
      REL_SRC_DIR_PATH: ./src
    steps:
      - uses: actions/checkout@v3

      - id: common
        uses: ghga-de/gh-action-common@v1.0.3

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run pytest
        run: |
          export ${{ steps.common.outputs.CONFIG_YAML_ENV_VAR_NAME }}="${{ steps.common.outputs.CONFIG_YAML }}"
          pytest \
            --cov="${REL_SRC_DIR_PATH}" \
            --cov-report=xml
