name: Unit and Integration Tests

on: push

jobs:
  unit_and_int_tests:
    runs-on: ubuntu-latest
    name: Unit and Integration Tests

    steps:
      - uses: actions/checkout@v3

      - name: Set up containers
        run: |
          docker-compose -f .devcontainer/docker-compose.yml up -d

      - name: Install Dependencies
        run: |
          docker exec \
            --workdir /workspace \
            archive-test-bed \
            sudo pip install -r requirements.txt \
            sudo pip install -r requirements-dev.txt

      - name: Run pytest
        run: |
          docker exec \
            --workdir /workspace \
            archive-test-bed \
            pytest
