name: Unit and Integration Tests

on: push

jobs:
  unit_and_int_tests:
    runs-on: ubuntu-latest
    name: Unit and Integration Tests
    env:
      REL_SRC_DIR_PATH: ./src
    steps:
      - uses: actions/checkout@v2.4.2

      - name: Set up containers
        run: |
          docker-compose -f .devcontainer/docker-compose.yml up -d

      - name: Install Dependencies
        run: |
          docker exec \
            --workdir /workspace \
            -it devcontainer_app_1 \
            sudo pip install -r requirements.txt

      - name: Run pytest
        run: |
          docker exec \
            --workdir /workspace \
            -it devcontainer_app_1 \
            pytest \
            --cov="${REL_SRC_DIR_PATH}" \
            --cov-report=xml
